export const CHANGE_ARTICLE_CONTENT = 'CHANGE_ARTICLE_CONTENT'

export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';
export const CREATE_ARTICLE_START = 'CREATE_ARTICLE_START';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';

export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL';
export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';

export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAIL = 'FETCH_ARTICLE_FAIL';
export const FETCH_ARTICLE_START = 'FETCH_ARTICLE_START';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';

export const INIT_EDITOR = 'INIT_EDITOR';

export const ENABLE_EDIT= 'ENABLE_EDIT';
export const DISABLE_EDIT = 'DISABLE_EDIT';

export const CLEAR_ARTICLE = 'CLEAR_ARTICLE';